# Generated by Django 4.1 on 2022-08-29 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='head_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
