# Generated by Django 4.1 on 2022-08-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_user_task_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_id',
        ),
    ]
